name: build_Release
on:
  push:
    branches:
      - kfd
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: '1.1.7b2'
 
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Procursus
        uses: wwg135/procursus-action@main
        with:
          packages: ldid trustcache make findutils coreutils

      - name: Install THEOS
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos

      - name: Set env
        run: |
          sT=$(TZ=UTC-8 date +'%S')
          echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
          echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}
          echo ${{ env.logT }}
      
      - name: Pre body
        run: |
          echo -e "[点击当前版本下载](https://github.com/wwg135/Taurine/releases/download/${{ env.msT }}/Taurine.ipa)" >> body.txt
          echo -e "\n更新时间：${{ env.logT }}" >> body.txt
          echo -e "\n**当前更新日志如下：**" >> body.txt
          echo -e "\n> - 同步官方更新" >> body.txt
      
      - name: Build ipa
        run: |
          set -x
          export THEOS=$HOME/theos
          gmake -j$(sysctl -n hw.physicalcpu)
          cd output
          zip -r ../${{github.workflow}}.ipa

      - name: Release ipa
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.msT }}
          target_commitish: kfd
          body_path: body.txt
          latest: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.ipa
